{% set name = "python-minifier" %}
{% set version = "2.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_minifier-{{ version }}.tar.gz
  sha256: ba8697b507b6ff059b4b43db2e08d8f9a6bd048d80ae3b955cd286092be2ffb2

build:
  number: 0
  noarch: python
  entry_points:
    - pyminify=python_minifier.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.11
    - setuptools_scm
  run:
    - python >=3.6,<3.11

test:
  imports:
    - python_minifier
    - python_minifier.rename
  commands:
    - pip check
    - pyminify --help
  requires:
    - pip

about:
  home: https://github.com/dflook/python-minifier
  summary: Transform Python source code into it's most compact representation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
